name: phishnet_app
description: A phishing detection app
publish_to: 'none'

environment:
  sdk: '>=3.7.0 <4.0.0'

dependencies:
 
  flutter:
    sdk: flutter
  http: ^0.13.5
  shared_preferences: ^2.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

fonts:
  - family: SpaceGrotesk
    fonts:
      - asset: assets/fonts/SpaceGrotesk-Regular.ttf
 
